trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'
variables:
  resource_group: RG-Smart-Hotel
  location: West Europe
  webapp_name: smh360007
  mysqlserver_name: smhmysql360007
  mysqldb_name: hotel_coupon
  admin_username: vmadmin
  admin_password: Password123$  


stages:
  - stage: Build
    displayName: 'Build Appli Coupon'
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'package'

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: |
                **/*.war
              TargetFolder: '$(build.artifactstagingdirectory)'
            condition: succeededOrFailed()
            
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Deploytest
    displayName: 'test du deploiement appli'
    condition: succeeded()
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: Deploy
        steps:
          - task: replacetokens@3
            inputs:
              targetFiles: '**/*.yml'
              encoding: 'auto'
              writeBOM: true
              escapeType: 'none'
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '__'
              tokenSuffix: '__'
              useLegacyPattern: false
              enableTelemetry: true

          - task: Ansible@0
            inputs:
              ansibleInterface: 'remoteMachine'
              connectionOverSsh: 'VmConnexionAnsible'
              playbookSourceRemoteMachine: 'agentMachine'
              playbookRootRemoteMachine: '$(Build.SourcesDirectory)/ansible'
              playbookPathLinkedArtifactOnRemoteMachine: 'main.yml'
              inventoriesRemoteMachine: 'hostList'
              inventoryHostListRemoteMachine: '137.116.94.5'
              failOnStdErr: false