

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build Appli Coupon'
    jobs:
      - job: Build
        displayName: Build
        steps:
          - 


  
    