trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  location: 'West Europe'
  resourceGroupName: 'RG-Smart-Hotel'
  webappName: 'smh360webd4040cc'
  mysqlServerName: 'smh360mysql40405cc'
  mysqlDbName: 'hotel_coupon'
  mysqlAdmin: 'vmadmin'
  mysqlAdminSecret: 'Password123$'

stages:
  - stage: Build
    displayName: 'Build Appli Coupon'
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'package'

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: |
                **/*.war
              TargetFolder: '$(build.artifactstagingdirectory)'
            condition: succeededOrFailed()
            
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Deploytest
    displayName: 'Test du déploiement'
    condition: succeeded()
    dependsOn: Build
    jobs:
    - deployment: DeploymentJob
      pool:
        vmImage: 'ubuntu-latest'
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
              - task: replacetokens@3
                inputs:
                  targetFiles: '**/*.yml'
                  encoding: 'auto'
                  writeBOM: true
                  escapeType: 'none'
                  actionOnMissing: 'warn'
                  keepToken: false
                  tokenPrefix: '__'
                  tokenSuffix: '__'
                  useLegacyPattern: false
                  enableTelemetry: true

              - task: Ansible@0
                inputs:
                  ansibleInterface: 'remoteMachine'
                  connectionOverSsh: 'VmConnexionAnsible'
                  playbookSourceRemoteMachine: 'agentMachine'
                  playbookRootRemoteMachine: '$(Build.SourcesDirectory)/ansible'
                  playbookPathLinkedArtifactOnRemoteMachine: 'main.yml'
                  inventoriesRemoteMachine: 'hostList'
                  inventoryHostListRemoteMachine: '137.116.94.5'
                  failOnStdErr: false

              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'AzureConnexion'
                  appType: 'webApp'
                  WebAppName: '$(webappName)'
                  #packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.war'
                  packageForLinux: '$(Pipeline.Workspace)/**/*.war'
                  AppSettings: '-SPRING_DATASOURCE_USERNAME $(mysqlAdmin)@$(mysqlServerName) -SPRING_DATASOURCE_PASSWORD $(mysqlAdminSecret) -SPRING_DATASOURCE_URL jdbc:mysql://$(mysqlServerName).mysql.database.azure.com:3306/hotel_coupon?useSSL=true&requireSSL=false'
                  TakeAppOfflineFlag: true
                  RemoveAdditionalFilesFlag: true
                      